In [2]:
import numpy as np
from numpy import *
arr=array([1,5.6,7,8],float)
print(arr.dtype)
print(arr)

float64
[1.  5.6 7.  8. ]


In [6]:
arr=np.arange(1,8,2)
print(arr)

[1 3 5 7]


In [11]:
logvalues = np.logspace(1, 3,5)


int_logvalues = logvalues.astype(int)
print(int_logvalues)


[  10   31  100  316 1000]


In [13]:
arr=zeros(4,int)
print(arr)

[0 0 0 0]


In [15]:
arr= zeros((2,4,6),int)
print(arr)

[[[0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]]

 [[0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]]]


In [16]:
arr= ones((3,4,4),int)
print(arr)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [18]:
list=[[1,2,3,4],[5,3,7,6]]
arr=np.array(list)
print(arr)

[[1 2 3 4]
 [5 3 7 6]]


In [19]:
matrix=np.full((4,3),8)
print(matrix)

[[8 8 8]
 [8 8 8]
 [8 8 8]
 [8 8 8]]


In [20]:
matrix=np.full(4,8)
print(matrix)

[8 8 8 8]


In [14]:
arr=ones(5,int)
print(arr)

[1 1 1 1 1]


In [8]:
arr=logspace(1,20,3)
print(arr)
print(arr[2])

[1.00000000e+01 3.16227766e+10 1.00000000e+20]
1e+20


In [21]:
matrix=np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
matrix=np.diag([1,2])
print(matrix)

[[1 0]
 [0 2]]


In [26]:
arr= np.random.rand(3)
print(arr)

[0.57519937 0.59460794 0.52534431]


In [30]:
arr= np.random.randint(5)
print(arr)

0


In [32]:
arr=np.random.rand(3,4,4)
print(arr)

[[[0.26127533 0.1715791  0.59804288 0.07937381]
  [0.73451813 0.52569521 0.43900294 0.89794852]
  [0.41407844 0.92759185 0.51317296 0.36979052]
  [0.29287481 0.65929935 0.85315999 0.6399959 ]]

 [[0.81950274 0.07724175 0.64752675 0.31174239]
  [0.09695282 0.79785861 0.349802   0.83821837]
  [0.29952746 0.60833378 0.31941321 0.69301581]
  [0.57155464 0.29239869 0.27199423 0.35780522]]

 [[0.62189202 0.85971525 0.62089198 0.05399718]
  [0.72570207 0.45256621 0.86391384 0.10568236]
  [0.59243723 0.63496302 0.11875969 0.77938425]
  [0.83715781 0.54399737 0.41617829 0.0136409 ]]]


In [33]:
arr=np.random.randint(0,10,10)
print(arr)

[9 0 3 2 6 0 8 8 0 0]


In [31]:
arr=np.random.rand(3,4,2)
print(arr)

[[[0.99477337 0.19300308]
  [0.55836532 0.82367246]
  [0.42425666 0.01803387]
  [0.55156302 0.1195069 ]]

 [[0.55319689 0.96701256]
  [0.31143133 0.39396385]
  [0.19598997 0.8923769 ]
  [0.20059617 0.93595896]]

 [[0.95007214 0.88800684]
  [0.24084121 0.77713181]
  [0.88909437 0.69771565]
  [0.62281013 0.65804127]]]


In [34]:
arr=np.random.randint(0,10,(2,2))
print(arr)

[[8 7]
 [9 8]]
